version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    commit-message:
      prefix: "chore"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      npm-minor:
        update-types:
          - "minor"
      npm-patch:
        update-types:
          - "patch"
